apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sandbox
  labels:
    app: k8s-sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-sandbox
  template:
    metadata:
      labels:
        app: k8s-sandbox
    spec:
      containers:
      - name: k8s-sandbox
        image: go-sandbox
        imagePullPolicy: IfNotPresent # localのimageを利用する場合に必要
        ports:
        - name: hello
          containerPort: 8081
        - name: goodbye
          containerPort: 8082
