apiVersion: v1
kind: Service
metadata:
  name: k8s-sandbox
spec:
  selector:
    app: k8s-sandbox
  type: NodePort
  ports:
  - name: hello
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30000
  - name: goodbye
    port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: 30001
